### ISSUE TITLE
bitbake server cannot start due to environment variable in bblayers.conf 

### ISSUE THREAD

**Issue by gerritavenant** [NetworkGradeLinux/mion#73] opened 2021-01-05 06:55 UTC
https://github.com/NetworkGradeLinux/mion/blob/6210e1be6560a35bebfc52e8e73cd35cb1de5100/build/conf/bblayers.conf#L22

Hi, it seems I cannot use any of the `bitbake` commands due to the `${VENDOR}` environment variable in `bblayers.conf`. Hard coding it to `stordis` gives the correct behaviour.

**Comment by kprosise** [comment] 2021-01-05 22:57
Hi @gerritavenant,  welcome and thank you for reporting! To help us reproduce the error, some additional information is required.

Was bitbake called directly?  (rather than using the `mc_build.sh` script)  
To use bitbake , `VENDOR=stordis` in `build/conf/local.conf` needs to be un-commented. If it was uncommented, could you provide us with:
*  the bitbake/build command used 
* the output of the build command with `-e`

**Comment by gerritavenant** [comment] 2021-01-06 14:15
Hi @kprosise 
Ah I see the `mc_build.sh` script wraps the environment variables for the bitbake build command. I used the `mc_build.sh` script to build, but then tried to use bitbake commands for further inspection.

I tried `bitbake-layers` - first to view layers and their priorities and then will also need it to add my own layer. 

It does not look like uncommenting `VENDOR=stordis` in `build/conf/local.conf` fixed it. I still get the following output when I run any bitbake command (`bitbake-layers` in this case)
```
NOTE: Starting bitbake server...
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/bfdev/mion-os/mion/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 31639 at 2021-01-06 13:42:39.957626 ---
ERROR: The following layer directories do not exist:
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf
ERROR: The following layer directories do not exist:
ERROR: The following layer directories do not exist:
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf

ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/bfdev/mion-os/mion/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 31639 at 2021-01-06 13:42:39.957626 ---
ERROR: The following layer directories do not exist:
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf
ERROR: The following layer directories do not exist:
ERROR: The following layer directories do not exist:
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR:    /home/bfdev/mion-os/mion/meta-mion-bsp/meta-mion-${VENDOR}
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf
ERROR: Please check BBLAYERS in /home/bfdev/mion-os/mion/build/conf/bblayers.conf
```

I have to fix it to be able run `bitbake -e`, find attached:
[bitbake_e.log](https://github.com/NetworkGradeLinux/mion/files/5776135/bitbake_e.log)

Maybe a solution would be for the mc_build.sh script to export these environment variables, but I'm having trouble to get it working.

**Comment by kprosise** [comment] 2021-01-07 19:50
@gerritavenant, thank you, and I was able to replicate the issue with the information you provided, so I'm hopeful that we'll figure this out soon!

 Also, if you're not already there, feel free to join us on [Slack](https://join.slack.com/t/networkgradelinux/shared_invite/zt-ktyqftox-yFOV8a7qdgDVvPADkc82tw).

**Comment by kprosise** [comment] 2021-01-08 21:42
@toganlabs, I've begun to look into this issue, if you could give this a quick look over and see if anything sticks out, it would be appreciated.

**Comment by kprosise** [comment] 2021-01-11 19:35
This appears to be a documentation issue, documentation will be updated soon to  reflect how to use bitbake commands.

**Comment by kprosise** [comment] 2021-01-13 16:05
@gerritavenant, The issue is that a number of variables need to be prepended to the bitbake command. `mion/README.md`  has been updated, he getting started guide will be updated soon.

**Comment by kprosise** [comment] 2021-01-13 18:31
Updated `mion/README.md` and `mion-docs/docs/getting-started.md` with information on how to pass variables to bitbake for mion. Waiting on PR approval before closing issue.

**Comment by kprosise** [comment] 2021-01-14 19:53
clarified use to be the same as the build in both getting-started and mion/README. closing issue.

**Closed as completed by kprosise** 2021-01-14 19:53 UTC
Labels: documentation
