### ISSUE TITLE
Create Mion root partition that uses the entire disk space during ONIE installation

### ISSUE THREAD

**Issue by frederic-loui** [NetworkGradeLinux/mion#69] opened 2020-12-13 18:39 UTC
Hi,
By default with ONIE installer for `stordis-bf2556x-1t` or `accton-wedge100bf-32x`:
- `Mion` is created in `/dev/sda3` partition 
-  with a size of 4G

Is it possible to consider an option where `Mion` is using the entire disk space left ?
The command used seemed to be:
```
    sgdisk --new="${part_num}::+${PART_SIZE_MB}MB" \
        --attributes="${part_num}:=:${gpt_attr_bitmask}" \
        --change-name="${part_num}:${VOLUME_LABEL}" "${blk_dev}" ||
            error "Unable to create partition ${part_num} on ${blk_dev}"
```

actually the command would be: (based on this [documentation](https://fedoramagazine.org/managing-partitions-with-sgdisk/) usage of **0** special meaning)
```
    sgdisk --new="${part_num}:0:0 \
        --attributes="${part_num}:=:${gpt_attr_bitmask}" \
        --change-name="${part_num}:${VOLUME_LABEL}" "${blk_dev}" ||
            error "Unable to create partition ${part_num} on ${blk_dev}"
```

> The value **0** has a special-case meaning for several of the fields:
> 
> - In the partition number field, **0** indicates that the next available number should be used (numbering starts at 1).
> 
> - In the starting address field, **0** indicates that the start of the largest available block of free space should be used. Some space at the start of the hard drive is always reserved for the partition table itself.
> 
> - In the ending address field, **0** indicates that the end of the largest available block of free space should be used.

Merci !
Frederic

**Comment by CommitThis** [comment] 2020-12-14 11:03
Duplicate of https://github.com/NetworkGradeLinux/meta-mion/issues/58

I will quote your message though, thanks. Will probably come in useful.

**Closed as completed by CommitThis** 2020-12-14 11:03 UTC
