### ISSUE TITLE
Define update strategy for all installation types

### ISSUE THREAD

**Issue by N-Mc-Nally** [NetworkGradeLinux/mion#90] opened 2021-01-27 16:07 UTC

**Comment by johntoomey** [comment] 2021-03-31 10:58
This needs to include out of tree kernel modules as mentioned here (issue closed as it is a duplicate of this): https://github.com/NetworkGradeLinux/mion/issues/93

**Comment by johntoomey** [comment] 2021-04-14 13:54
started defining the document here: https://github.com/NetworkGradeLinux/mion-docs/wiki/Mion-update-strategy

**Comment by johntoomey** [comment] 2021-04-21 10:02
this is as done as it can be - initial version of the strategy outlined above
- the tl;dr is that we will update the submodules weekly and users will need to build and install a new image using ONIE

next steps are to start looking at what needs to be done this release to set up the groundwork for updates using a package manager - details [here](https://github.com/NetworkGradeLinux/mion/issues/117) and meeting scheduled for monday the 26th of april

**Closed as completed by johntoomey** 2021-04-21 10:02 UTC
Labels: high
