### ISSUE TITLE
APS(formerlySTORDIS) BF2556X-1T image creation failure

### ISSUE THREAD

**Issue by frederic-loui** [NetworkGradeLinux/mion#67] opened 2020-12-12 12:09 UTC
HI, (Still testing/following documentation)

I created an environment based on pre-requisite and tried to create ONIE ONLPv1 image for `stordis-bf2556x-1t`, as seen before it yields `git fetch error`. this can be corrected but it would be great if `https` method could be used by default.

Otherwise, people will simply abandon the idea to give a try to Mion ...

If not possible, it would be great to indicate where to change the `git fetch` method.

A bientôt,
Frederic

```
../mc_build.sh -m stordis-bf2556x-1t -h host-onie:mion-onie-image-onlpv1
WARNING: /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv1/onlpv1_1.0.bb: Exception during build_dependencies for S00:12
WARNING: /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv1/onlpv1_1.0.bb: Error during finalise of /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv1/onlpv1_1.0.bb
WARNING: /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv2/onlpv2_1.0.bb: Exception during build_dependencies for S00:11
WARNING: /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv2/onlpv2_1.0.bb: Error during finalise of /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv2/onlpv2_1.0.bb
ERROR: ExpansionError during parsing /home/p4/mion/meta-mion/meta-mion/recipes-platform/onlpv2/onlpv2_1.0.bb     | ETA:  0:00:09
Traceback (most recent call last):
  File "/home/p4/mion/bitbake/lib/bb/fetch2/__init__.py", line 1177, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f8c81d68370>, d=<bb.data_smart.DataSmart object at 0x7f8c81a0af70>, name='onl'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/p4/mion/bitbake/lib/bb/fetch2/__init__.py", line 1592, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f8c81d68370>, d=<bb.data_smart.DataSmart object at 0x7f8c81a0af70>, name='onl'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/p4/mion/bitbake/lib/bb/fetch2/git.py", line 631, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f8c81d68370>, d=<bb.data_smart.DataSmart object at 0x7f8c81a0af70>, name='onl'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/p4/mion/bitbake/lib/bb/fetch2/git.py", line 620, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f8c81d68370>, d=<bb.data_smart.DataSmart object at 0x7f8c81a0af70>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/p4/mion/bitbake/lib/bb/fetch2/__init__.py", line 894, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export PATH="/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python-native:/home/p4/mion/openembedded-core/scripts:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/x86_64-mion-linux:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/p4/mion/bitbake/bin:/home/p4/mion/build/tmp-glibc/hosttools"; export HOME="/home/p4"; git -c core.fsyncobjectfiles=0 ls-remote ssh://git@github.com/APS-Networks/OpenNetworkLinuxv2.git ', d=<bb.data_smart.DataSmart object at 0x7f8c810d6eb0>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export PATH="/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python-native:/home/p4/mion/openembedded-core/scripts:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/x86_64-mion-linux:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/p4/mion/build/tmp-glibc/work/stordis_bf2556x_1t-mion-linux/onlpv2/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/p4/mion/bitbake/bin:/home/p4/mion/build/tmp-glibc/hosttools"; export HOME="/home/p4"; git -c core.fsyncobjectfiles=0 ls-remote ssh://git@github.com/APS-Networks/OpenNetworkLinuxv2.git  failed with exit code 128, output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



Summary: There were 4 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by CommitThis** [comment] 2020-12-12 12:59
Hi Frederic, this appears to be the same issue as #66.
I suggest we track the issue there.

**Comment by CommitThis** [comment] 2020-12-12 13:27
Closing as duplicate of #66

**Closed as completed** 2020-12-12 13:27 UTC
